### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by sad** [nihilist/arena.tapes.ws#1]
- [ ] battles
  - [ ] battle creation page
  - [ ] active battle page
  - [ ] battle voting/results page
  - [ ] view previous battles
  - [x] add blind vote option for battles
  - [ ] transcode all battle submissions to mp3 or something idk
  - [x] page to suggest rules/submit samples
  - [ ] view ruleset/sample submissions in battle creator
  - [ ] vote to disqualify user
  - [ ] countdown until battle start

- [ ] misc
  - [ ] email with @sendgrid/mail 
  - [ ] onboarding
  - [ ] desktop notifications
  - [x] extend ops functionality
  - [x] winrate % on profiles
  - [x] show/hide winrate % and battles participated in
  - [x] config.json 
  - [x] permission management
  - [x] fix security issues
  - [ ] csurf
  - [x] page titles
  - [ ] per user invites
  - [x] complete header partial including navbar + flash message
  - [x] proper 404/error pages
